language: python
sudo: false
notifications:
  email: false
  python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - 3.5-dev
  before_install:
  install:
  - pip install watson-developer-cloud
  - pip install numpy
  - pip install PRAW
  script:
  after_success:
