language: python
sudo: false
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
install:
  - pip install watson-developer-cloud
  - pip install numpy
  - pip install PRAW
script: echo foo
